version: "3"
services:
  db:
    image: "postgres"
    container_name: "hitdice-db"
    environment:
      - POSTGRES_USER=hitdice
      - POSTGRES_PASSWORD=0wlbear
      - POSTGRES_DB=hitdice
    ports:
      - "5432:5432"
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data